
services:

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
        - ./.data/docker/postgres/data:/var/lib/postgresql/data/
    networks:
      - postgres-net

networks:
  postgres-net:
  proxy-net:
    
