name: Docker Image CI

on:
  push:
  pull_request:
  schedule:
    - cron: '00 6 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make docker/build
