name: RustSec

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run audit
        run: make audit
        continue-on-error: true
