name: Test & Build

on:
  push:
  pull_request:
  schedule:
    - cron: '00 6 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps
    
    - name: Run tests
      run: make test
    
    - name: Build
      run: make build
